/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "secondary": "#575e72",
        "surface": "#f9f9ff",
        "on-background": "#121c2a",
        "secondary-fixed": "#dbe2fa",
        "primary-container": "#6063ee",
        "on-secondary-container": "#5d6478",
        "on-primary": "#ffffff",
        "primary": "#4648d4",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#703700",
        "on-surface-variant": "#464554",
        "surface-container-low": "#eff3ff",
        "on-tertiary-container": "#fffbff",
        "surface-container-high": "#dee9fd",
        "surface-container-highest": "#d9e3f7",
        "inverse-primary": "#c0c1ff",
        "secondary-container": "#dbe2fa",
        "surface-container": "#e6eeff",
        "outline": "#767586",
        "background": "#f9f9ff",
        "on-surface": "#121c2a",
        "secondary-fixed-dim": "#bfc6dd",
        "tertiary-fixed-dim": "#ffb783",
        "error-container": "#ffdad6",
        "surface-tint": "#494bd6",
        "inverse-surface": "#273140",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "tertiary-fixed": "#ffdcc5",
        "outline-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed": "#301400",
        "surface-dim": "#d0daef",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#141b2c",
        "inverse-on-surface": "#ebf1ff",
        "surface-variant": "#d9e3f7",
        "tertiary-container": "#b55d00",
        "surface-bright": "#f9f9ff",
        "tertiary": "#904900",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#3f4759",
        soft: {
          indigo: "#4648d4",
          teal: "#6063ee",
          green: "#22c55e",
          red: "#ef4444",
          amber: "#f59e0b",
          gray: "#767586",
        },
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "body-md": ["Manrope"],
        "subtext-sm": ["Manrope"],
        "label-caps": ["Manrope"],
        "headline-xl": ["Manrope"],
        "headline-lg": ["Manrope"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "subtext-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "300" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        neo: "6px 6px 12px rgba(70, 72, 212, 0.3), -4px -4px 8px rgba(255, 255, 255, 0.2)",
        "neo-sm": "3px 3px 8px rgba(174, 174, 192, 0.3), -3px -3px 8px rgba(255, 255, 255, 0.8)",
        "neo-inset": "inset 2px 2px 5px rgba(18, 28, 42, 0.05), inset -2px -2px 5px rgba(255, 255, 255, 0.8), 2px 2px 5px rgba(18, 28, 42, 0.02)",
        glass: "0 20px 40px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};
